 swagger: '2.0'
 info:
   title: Your API
   version: 1.0
 basePath: /
 schemes:
   - http
 securityDefinitions:
   Bearer:
     type: apiKey
     name: Authorization
     in: header
 security:
   - Bearer: []